TARGET_FORCES = [
    "Avon and Somerset Constabulary",
    "Bedfordshire Police",
    "British Transport Police",
    "Cambridgeshire Constabulary",
    "Cheshire Constabulary",
    "City of London Police",
    "Cleveland Police",
    "Cumbria Constabulary",
    "Derbyshire Constabulary",
    "Devon & Cornwall Police",
    "Dorset Police",
    "Durham Constabulary",
    "Dyfed-Powys Police",
    "Essex Police",
    "Gloucestershire Constabulary",
    "Gwent Police",
    "Hampshire Constabulary",
    "Hertfordshire Constabulary",
    "Humberside Police",
    "Kent Police",
    "Lancashire Constabulary",
    "Leicestershire Police",
    "Lincolnshire Police",
    "Merseyside Police",
    "Metropolitan Police Service",
    "Norfolk Constabulary",
    "North Wales Police",
    "North Yorkshire Police",
    "Northamptonshire Police",
    "Police Service of Northern Ireland",
    "Northumbria Police",
    "Nottinghamshire Police",
    "South Wales Police",
    "South Yorkshire Police",
    "Staffordshire Police",
    "Suffolk Constabulary",
    "Surrey Police",
    "Sussex Police",
    "Thames Valley Police",
    "Warwickshire Police",
    "West Mercia Police",
    "West Midlands Police",
    "West Yorkshire Police",
    "Wiltshire Police",
]

FORCE_ALIASES = {
    "avon and somerset": "Avon and Somerset Constabulary",
    "avon somerset": "Avon and Somerset Constabulary",
    "bedfordshire": "Bedfordshire Police",
    "british transport": "British Transport Police",
    "btp": "British Transport Police",
    "cambridgeshire": "Cambridgeshire Constabulary",
    "cheshire": "Cheshire Constabulary",
    "city of london": "City of London Police",
    "cleveland": "Cleveland Police",
    "cumbria": "Cumbria Constabulary",
    "derbyshire": "Derbyshire Constabulary",
    "devon and cornwall": "Devon & Cornwall Police",
    "devon cornwall": "Devon & Cornwall Police",
    "dorset": "Dorset Police",
    "durham": "Durham Constabulary",
    "dyfed powys": "Dyfed-Powys Police",
    "essex": "Essex Police",
    "gloucestershire": "Gloucestershire Constabulary",
    "gwent": "Gwent Police",
    "hampshire": "Hampshire Constabulary",
    "hertfordshire": "Hertfordshire Constabulary",
    "humberside": "Humberside Police",
    "kent": "Kent Police",
    "lancashire": "Lancashire Constabulary",
    "lancs police": "Lancashire Constabulary",
    "leicestershire": "Leicestershire Police",
    "lincolnshire": "Lincolnshire Police",
    "merseyside": "Merseyside Police",
    "metropolitan police service": "Metropolitan Police Service",
    "metropolitan police": "Metropolitan Police Service",
    "met police": "Metropolitan Police Service",
    "norfolk": "Norfolk Constabulary",
    "north wales": "North Wales Police",
    "north yorkshire": "North Yorkshire Police",
    "northamptonshire": "Northamptonshire Police",
    "police service of northern ireland": "Police Service of Northern Ireland",
    "psni": "Police Service of Northern Ireland",
    "northern ireland": "Police Service of Northern Ireland",
    "northumbria": "Northumbria Police",
    "nottinghamshire": "Nottinghamshire Police",
    "south wales": "South Wales Police",
    "south yorkshire": "South Yorkshire Police",
    "south yorkshre": "South Yorkshire Police",
    "staffordshire": "Staffordshire Police",
    "suffolk": "Suffolk Constabulary",
    "surrey": "Surrey Police",
    "sussex": "Sussex Police",
    "thames valley": "Thames Valley Police",
    "warwickshire": "Warwickshire Police",
    "west mercia": "West Mercia Police",
    "west midlands": "West Midlands Police",
    "west yorkshire": "West Yorkshire Police",
    "wiltshire": "Wiltshire Police",
}
